### ISSUE TITLE
This is a virus

### ISSUE THREAD

**Issue by nocryptoinjectorspls** [master131/ExtremeInjector#80]
Do not download this program. If you have downloaded this you can fix it. Add me on Discord mrreddot#7902
master131 chat with me if I'm wrong. The hash is different on both sites. Look at the "Virus Total", Microsoft even caught it as a Trojan:Win32/CryptInject.

**Comment by master131** [comment]
@nocryptoinjectorspls As I have explained multiple times - there is no crypto miner in the official version of Extreme Injector.

The best analogy I can provide is that:
1. You went online and purchased an iPhone from an unknown website people have not heard of before.
2. You eventually receive a big package at your door and open it.
3. The box contains 10 snakes and a real iPhone with the original packaging inside.
4. You then go and call Apple and blow up their social media because you got snakes at your doorstep even though you did not purchase the product at an authorised retailer.

Can you see the issue here now? I don't understand why I am being harassed about something that has nothing to do with me.

As for the Microsoft detection, it's probably because now they've incorrectly associated the original Extreme Injector with the dodgy one. Note that all other AV vendors still detect it as an injector or hack tool.
